#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

RUN_ID="${RUN_ID:-jepa_moderate_4k_448}" \
MODEL_DIM=448 \
NUM_LAYERS=9 \
NUM_HEADS=8 \
NUM_KV_HEADS=4 \
MLP_MULT=2 \
ITERATIONS=4000 \
MAX_WALLCLOCK_SECONDS=0 \
TARGET_GLOBAL_TOKENS=65536 \
GRAD_ACCUM_STEPS=1 \
USE_SWIGLU=1 \
QK_GAIN_INIT=5.0 \
DISTILL_ENABLED=1 \
DISTILL_WEIGHT=0.06 \
DISTILL_TEMP=2.0 \
DISTILL_START_FRAC=0.72 \
DISTILL_START_STEP=-1 \
DISTILL_START_WALLCLOCK_FRAC=-1 \
DISTILL_EMA_DECAY=0.999 \
JPCR_ENABLED=1 \
JPCR_HIDDEN=64 \
JPCR_PROJ_DIM=32 \
JPCR_WEIGHT=0.08 \
JPCR_BLEND_INIT=-2.0 \
JPCR_LR=0.02 \
JPCR_WARMUP_STEPS=100 \
INTRA_LOOP_START=3 \
INTRA_LOOP_END=5 \
INTRA_LOOP_STEPS=2 \
BIGRAM_RANK=0 \
RESIDUAL_NGRAM_ENABLED=0 \
QUANT_SCHEME=int8 \
MIXED_LOW_PRECISION_SCHEME=int8 \
GPTQ=1 \
SWA_ENABLED=1 \
bash ./phase4_fixed_submission.sh